[tool.black]
line-length = 110
target-version = ['py38']

[tool.poetry]
name = "helm-mutualized"
version = "0.0.0"
description = "HELM chart to use the mutualized infrastructure"
authors = ["Camptocamp <info@camptocamp.com>"]
