{{ $fullname := include "common.fullname" ( dict "root" . "service" .Values ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}-env
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
  annotations: {{- toYaml .Values.envConfigMap.annotations | nindent 4 }}
data:
  CHART_NAME: {{ .Chart.Name }}
  RELEASE_NAME: {{ .Release.Name }}
  RELEASE_NAMESPACE: {{ .Release.Namespace }}
{{- if .Values.ingress.enabled }}
  INGRESS_HOST: {{ (index .Values.ingress.hosts 0).host }}
{{- end }}
  CONFIG_PATH: {{.Values.config.path | quote }}
  CONFIG_IMAGE_TAG: {{ .Values.config.image.tag | quote }}
  PRINT_IMAGE_TAG: {{ .Values.print.image.tag | quote }}
  PRINT_LOGS_IMAGE_TAG: {{ .Values.logs.image.tag | quote }}
  TILECLOUDCHAIN_IMAGE_TAG: {{ .Values.tilecloudchain.image.tag | quote }}
  CONFIG_SERVICE_NAME: {{ include "common.fullname" ( dict "root" . "service" .Values.config ) }}
  PRINT_SERVICE_NAME: {{ include "common.fullname" ( dict "root" . "service" .Values.print ) }}
  PRINT_LOGS_SERVICE_NAME: {{ include "common.fullname" ( dict "root" . "service" .Values.logs ) }}
  TILECLOUDCHAIN_SERVICE_NAME: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}
