{{- if .Values.statsd.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.dbstats ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.dbstats ) | nindent 4 }}
spec:
  schedule: "{{ mod (regexReplaceAll "[a-f]+" (printf "%s-%s" .Release.Namespace .Release.Name | sha256sum) "" | trunc 5) 60 }} * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.dbstats ) | nindent 6 }}
  jobTemplate:
    spec:
      backoffLimit: 0
      template:  # POD level
        metadata:
          labels: {{ include "common.labels" ( dict "root" . "service" .Values.dbstats ) | nindent 12 }}
        spec:
          containers:
            - name: dbstats
              {{- include "common.containerConfig" ( dict "root" . "container" .Values.dbstats ) | nindent 14 }}
              args:
                - bash
                - -cxe
                - |
                  {{- if .Values.dbstats.prometheus }}
                  TARGET="--prometheus_instance={{ .Release.Namespace }}-{{ template "common.fullname" ( dict "root" . "service" .Values ) }} --prometheus_url={{ .Values.dbstats.prometheus }}"
                  {{- else }}
                  TARGET="--statsd_address={{ .Values.statsd.url }} --statsd_prefix=dbstats"
                  {{- end }}
                  export STATSD_TAG_DB=$(PGDATABASE)
                  c2cwsgiutils-stats-db \
                    --db=postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDATABASE) \
                    --verbosity WARNING \
                    --schema=public \
                    ${TARGET}
          restartPolicy: Never
{{- end }}
