{{- if .Values.c2c.statsd.enabled }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ template "mapfishprint.fullname" . }}-dbstats
  labels: &labels
    app: {{ template "mapfishprint.fullname" . }}
    chart: {{ template "mapfishprint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: dbstats
spec:
  schedule: "{{ mod (regexReplaceAll "[a-f]+" (printf "%s-%s" .Release.Namespace .Release.Name | sha256sum) "" | trunc 5) 60 }} * * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:  # POD level
        metadata:
          labels: *labels
        spec:
          {{- include "common.podConfig" (dict "service" .Values.print "root" .) | indent 10 }}
          containers:
            - name: dbstats
              image: ghcr.io/camptocamp/c2cwsgiutils:4
              imagePullPolicy: Always
              env:
              {{- range $name, $value := .Values.c2c.statsd.dbstats.env }}
                - name: {{ $name | quote }}
                  value: {{ $value | quote }}
              {{- end }}
                {{- if .Values.c2c.sentry.enabled }}
                - name: SENTRY_URL
                  value: https://{{ .Values.c2c.sentry.key }}@{{ .Values.c2c.sentry.hostname }}/{{ .Values.c2c.sentry.project }}
                - name: SENTRY_CLIENT_RELEASE
                  value: {{ .Values.image.tag | quote }}
                - name: SENTRY_CLIENT_ENVIRONMENT
                  value: {{ .Release.Name }}
                - name: SENTRY_TAG_SERVICE
                  value: dbstats
                {{- end }}
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: hostnameSlave
                - name: PGDATABASE
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: database
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: username
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgresql.secret }}
                      key: password
                - name: STATSD_USE_TAGS
                  value: "1"
                - name: STATSD_TAG_CHART
                  value: {{ .Chart.Name }}
                - name: STATSD_TAG_RELEASE
                  value: {{ .Release.Name }}
                {{- if .Values.c2c.statsd.dbstats.prometheus }}
                - name: STATSD_TAG_NAMESPACE
                  value: {{ .Release.Namespace }}
                {{- end }}
              args:
                - bash
                - -cxe
                - |
                  {{- if .Values.c2c.statsd.dbstats.prometheus }}
                  TARGET="--prometheus_instance={{ .Release.Namespace }}-{{ template "mapfishprint.fullname" . }} --prometheus_url={{ .Values.c2c.statsd.dbstats.prometheus }}"
                  {{- else }}
                  TARGET="--statsd_address={{ .Values.c2c.statsd.url }} --statsd_prefix=dbstats"
                  {{- end }}
                  export STATSD_TAG_DB=$(PGDATABASE)
                  c2cwsgiutils-stats-db \
                    --db=postgresql://$(PGUSER):$(PGPASSWORD)@$(PGHOST):5432/$(PGDATABASE) \
                    --verbosity WARNING \
                    --schema=public \
                    ${TARGET}
              {{- include "common.containerConfig" (dict "service" .Values.c2c.statsd.dbstats "root" .) | indent 14 }}
          restartPolicy: Never
{{- end }}
