{{- range $source, $repository := $.Values.additionalWebhooks.repositories }}
apiVersion: camptocamp.com/v4
kind: GitHubWebhook{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values.additionalWebhooks ) }}-{{ $source }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values.additionalWebhooks ) | nindent 2 }}
spec:
  contentType: json
  repository: {{ $repository }}
  secret: {{ $.Values.additionalWebhooks.secret }}
  url: {{ $.Values.additionalWebhooks.base_url }}{{ $source }}
{{- end }}
