{{- if .Values.home.enabled }}
{{ $fullname := include "common.fullname" ( dict "root" . "service" .Values.home ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.home ) }}-html
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.home ) | nindent 4 }}
  annotations: {{- toYaml .Values.envConfigMap.annotations | nindent 4 }}
data:
  {{- $currentScope := .}}
  {{- range $path, $p2 := .Files.Glob "home/html/**" }}
  {{- with $currentScope }}
  {{ substr ( len "home/html/" ) 999 $path }}: |
    {{- tpl ( .Files.Get $path ) . | nindent 4 }}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.home ) }}-config
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.home ) | nindent 4 }}
  annotations: {{- toYaml .Values.envConfigMap.annotations | nindent 4 }}
data:
  {{- ( .Files.Glob "home/config/**" ).AsConfig | nindent 2 }}
{{- end }}
