{{- if .Values.server.enabled }}
{{- if .Values.server.home.enabled }}
{{ $fullname := include "common.fullname" ( dict "root" . "service" .Values.server.home ) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.server.home "serviceName" "html" ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.server.home "serviceName" "html" ) | nindent 2 }}
data:
  {{- $currentScope := .}}
  {{- range $path, $p2 := .Files.Glob "home/html/**" }}
  {{- with $currentScope }}
  {{ substr ( len "home/html/" ) 999 $path }}: |
    {{- tpl ( .Files.Get $path ) . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
