{{- if .Values.ingress.enabled -}}
{{- $fullName := include "common.fullname" ( dict "root" . "service" .Values ) -}}
{{- $svcPrintPort := .Values.print.service.port -}}
{{- $svcLogsPort := .Values.logs.service.port -}}
{{- $svcConfigPort := .Values.config.service.port -}}
{{- range $ingress_host := .Values.ingress.hosts }}
---
{{- if semverCompare ">=1.19.0" ( trimPrefix "v" $.Capabilities.KubeVersion.Version ) }}
apiVersion: networking.k8s.io/v1
{{- else -}}
{{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-{{ $ingress_host.name }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values ) | nindent 4 }}
  {{- with $.Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if $ingress_host.tls }}
  tls:
    - hosts:
        - {{ $ingress_host.host }}
      secretName: {{ $ingress_host.tls.secretName }}
{{- end }}
  rules:
    - host: {{ $ingress_host.host }}
      http:
        paths:
        {{- range $.Values.ingress.paths }}
          - path: {{ . }}
            {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPrintPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPrintPort }}
              {{- end }}
          - path: {{ . }}print/logs
            {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-logs
                port:
                  number: {{ $svcLogsPort }}
              {{- else }}
              serviceName: {{ $fullName }}-logs
              servicePort: {{ $svcLogsPort }}
              {{- end }}
          - path: {{ . }}config
            {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-config
                port:
                  number: {{ $svcConfigPort }}
              {{- else }}
              serviceName: {{ $fullName }}-config
              servicePort: {{ $svcConfigPort }}
              {{- end -}}
        {{- end }}
{{- end }}
{{- end }}
