{{- if .Values.logs.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.logs ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.logs ) | nindent 4 }}
  {{- with .Values.logs.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.logs.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.logs ) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.logs ) | nindent 8 }}
      {{- with .Values.logs.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.podConfig" ( dict "root" . "service" .Values.logs ) | nindent 6 }}
      containers:
        - name: logs
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.logs ) | nindent 10 }}
          volumeMounts:
            - mountPath: /master_config
              name: master-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /logs/c2c/health_check
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /logs/c2c/health_check?max_level=0
              port: http
            initialDelaySeconds: 20
            failureThreshold: 50
            periodSeconds: 120
      volumes:
        - name: master-config
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.config ) }}
{{- end }}
