{{- if .Values.logs.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.logs ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.logs ) | nindent 2 }}
spec:
  replicas: {{ .Values.logs.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 0 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.logs ) | nindent 6 }}
  template:
    metadata: {{- include "common.podMetadata" ( dict "root" . "service" .Values.logs ) | nindent 6 }}
    spec:
      {{- include "common.podConfig" ( dict "root" . "service" .Values.logs ) | nindent 6 }}
      containers:
        - name: logs
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.logs ) | nindent 10 }}
          volumeMounts:
            - mountPath: /master_config
              name: master-config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.logs.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.logs.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: master-config
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.sharedConfig ) }}
{{- end }}
