apiVersion: v1
kind: Service
metadata:
  name: {{ template "mapfishprint.fullname" . }}-print
  labels:
    app: {{ template "mapfishprint.fullname" . }}
    chart: {{ template "mapfishprint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: print
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "mapfishprint.fullname" . }}
    release: {{ .Release.Name }}
    service: print
