---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "mapfishprint.fullname" . }}-print-pdb
  labels:
    app: {{ template "mapfishprint.fullname" . }}
    chart: {{ template "mapfishprint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: print-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "mapfishprint.fullname" . }}
      service: print
