apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "common.fullname" ( dict "root" . "service" .Values.print ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.print ) | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.print ) | nindent 6 }}
