{{- if .Values.print.enabled }}
{{- if .Values.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.print ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.print ) | nindent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $.Values.print ) | nindent 6 }}
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus
{{- end }}
{{- end }}
