{{- if .Values.redirect.enabled }}
apiVersion: camptocamp.com/v3
kind: SharedConfigConfig{{ .Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.redirectConfig ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.redirectConfig ) | nindent 2 }}
spec:
  matchLabels:
    mutualize-redirect-hosts: 'true'
  configmapName: hosts.yaml
  property: sources
{{- end }}
