{{- if .Values.server.enabled }}
{{- if .Values.server.redirect.enabled }}
apiVersion: camptocamp.com/v4
kind: SharedConfigConfig{{ .Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.server.redirect "serviceName" "redirect" ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.server.redirect "serviceName" "redirect" ) | nindent 2 }}
spec:
  matchLabels:
    mutualize-redirect-hosts{{ $.Values.postfix }}: 'true'
  configmapName: hosts.yaml
  property: sources
{{- end }}
{{- end }}
