{{- if .Values.rbac }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values ) | nindent 2 }}
rules:
- apiGroups:
    - camptocamp.com
  resources:
    - sharedconfigconfigs
    - sharedconfigsources
    - githubwebhooks
  verbs:
    - get
    - watch
    - list
    - create
    - update
    - patch
    - delete
{{- end }}
