apiVersion: v1
kind: Secret
type: Generic
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
data:
  id_rsa: {{ .Values.sshKey | b64enc }}
