{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "apache.serviceAccountName" . }}
  labels:
{{ include "apache.labels" . | indent 4 }}
{{- end }}
