{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mutualize.serviceAccountName" . }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values ) | nindent 4 }}
{{- end }}
