apiVersion: v1
kind: Service
metadata:
  name: {{ include "mutualized.fullname" . }}
  labels:
{{ include "mutualized.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.mutualizedExporter.enabled }}
    - port: 9117
      targetPort: prometheus
      protocol: TCP
      name: prometheus
{{- end }}
  selector:
    {{- include "mutualized.selectorLabels" . | nindent 4 }}
