apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.config ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.config ) | nindent 4 }}
spec:
  type: {{ .Values.config.service.type }}
  ports:
    - port: {{ .Values.config.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.config ) | nindent 4 }}
