{{- range $name, $value := .Values.config.sharedConfigs }}
---
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
  {{- range $name, $value := .labels }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
spec:
  name: {{ $name }}
  content:
    {{- toYaml .content | nindent 4 }}
    {{- if hasKey . "env" }}
    template_engines:
      - type: shell
        environment_variables: true
        {{- with .env }}
        data:
          {{- range $name, $value := . }}
          - name: {{ $name | quote }}
            value: {{ . | quote }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
{{- with $.Values.config.printConfigs }}
{{- range $name, $value := .sources }}
---
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
    mutualize-sharedconfig{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}
  content:
    type: git
    repo: git@github.com:{{ $value.repo }}.git
    branch: {{ default "master" $value.branch }}
    sub_dir: {{ default "" $value.sub_dir }}
    tags:
      - print
    {{- if hasKey . "template_engines" }}
    template_engines:
    {{- range $value.template_engines }}
      - type: shell
        environment_variables: true
        {{- with .dest_sub_dir }}
        dest_sub_dir: {{ . | quote }}
        {{- end }}
        {{- with .data }}
        data:
          {{- range $name, $value := . }}
          - name: {{ $name | quote }}
            value: {{ . | quote }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- with $.Values.config.tileCloudChainConfigs }}
{{- range $name, $value := .sources }}
---
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
    mutualize-sharedconfig{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}
  content:
    type: git
    repo: git@github.com:{{ $value.repo }}.git
    branch: {{ default "master" $value.branch }}
    sub_dir: {{ default "" $value.sub_dir }}
    tags:
      - print
    {{- if hasKey . "template_engines" }}
    template_engines:
    {{- range $value.template_engines }}
      - type: shell
        environment_variables: true
        {{- with .dest_sub_dir }}
        dest_sub_dir: {{ . | quote }}
        {{- end }}
        {{- with .data }}
        data:
          {{- range $name, $value := . }}
          - name: {{ $name | quote }}
            value: {{ . | quote }}
          {{- end }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- range $host_name, $host := $value.hosts }}
---
{{- $used_name := printf "%s-%s" $name $host_name }}
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $used_name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $used_name ) | nindent 4 }}
    mutualize-tilecloudchain-hosts{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}-{{ $host_name }}
  content:
    {{ $host }}: /etc/tilecloudchain-configs/{{ $name }}/config.yaml
{{- end }}
{{- end }}
{{- end }}
{{- with $.Values.config.redirectConfigs }}
{{- if ( .hosts | default false ) }}
---
apiVersion: camptocamp.com/v3
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" "redirect" ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values "serviceName" "redirect"  ) | nindent 2 }}
    mutualize-redirect-hosts{{ $.Values.postfix }}: 'true'
spec:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" "redirect" ) }}
  content:
    {{- toYaml .hosts | nindent 4 }}
{{- end }}
{{- end }}
