apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mapfishprint.fullname" . }}-shared-config
  labels:
    app: {{ template "mapfishprint.fullname" . }}
    chart: {{ template "mapfishprint.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    service: shared-config
  {{- if .Values.openshift }}
  annotations:
    image.openshift.io/triggers: |
      [
        {{ template "mapfishprint.trigger" (dict "image" "config" "tag" .Values.config.image.tag "container" "shared-config" "root" . ) }}
      ]
  {{- end }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "mapfishprint.fullname" . }}
      release: {{ .Release.Name }}
      service: shared-config
  template:
    metadata:
      labels:
        app: {{ template "mapfishprint.fullname" . }}
        release: {{ .Release.Name }}
        service: shared-config
    spec:
      {{- include "common.podConfig" (dict "service" .Values.config "root" .) | indent 6 }}
      containers:
        - name: shared-config
          {{- template "sharedConfig" (dict "service" "config_api" "root" .) }}
            - name: API_MASTER
              value: "1"
          {{- range $name, $value := .Values.config.slave.env }}
            - name: {{ $name | quote }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /scm/c2c/health_check
              port: http
            initialDelaySeconds: 10
          securityContext:
            runAsNonRoot: true
            {{- if not .Values.openshift }}
            runAsUser: 33  # www-data
            {{- end }}
          volumeMounts:
            - name: ssh-key
              readOnly: true
              mountPath: "/var/www/.ssh2"
          {{- include "common.containerConfig" (dict "service" .Values.config "root" .) | indent 10 }}
      volumes:
        - name: ssh-key
          secret:
            secretName: secrets-ssh-key
            defaultMode: 0440
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
