{{/* start range over sharedConfigs */}}
{{- range $name, $value := .Values.config.sharedConfigs }}
---
apiVersion: camptocamp.com/v4
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
  {{- range $name, $value := .labels }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
spec:
  name: {{ $name }}
  {{- with $value.external_secret }}
  external_secret:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  content:
    {{- toYaml .content | nindent 4 }}
    {{- if hasKey . "env" }}
    template_engines:
      - type: shell
        environment_variables: true
        {{- with .env }}
        data:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}  {{/* end if hasKey . "env" */}}
    {{ with .auth }}
    auth:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}  {{/* end range over sharedConfigs */}}
{{- with $.Values.config.printConfigs }}
{{/* start range over printConfigs.sources */}}
{{- range $name, $value := .sources }}
---
apiVersion: camptocamp.com/v4
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
    mutualize-sharedconfig{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}
  {{- with $value.external_secret }}
  external_secret:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  content:
    type: git
    repo: git@github.com:{{ $value.repo }}.git
    {{- with $value.branch }}
    branch: {{ . | quote }}
    {{- end }}
    {{- with $value.sub_dir }}
    sub_dir: {{ . | quote }}
    {{- end }}
    tags:
      - print
    {{- if hasKey . "template_engines" }}
    template_engines:
    {{- range $value.template_engines }}
      - type: shell
        environment_variables: true
        {{- with .dest_sub_dir }}
        dest_sub_dir: {{ . | quote }}
        {{- end }}
        {{- with .data }}
        data:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}  {{/* end range over template_engines */}}
    {{- end }}  {{/* end if hasKey . "template_engines" */}}
    auth:
      github_repository: {{ $value.repo }}
      # The type of access to check (admin|push|pull).
      github_access_type: {{ $value.github_access_type | default "push" }}
{{- end }}  {{/* end range over printConfigs.sources */}}
{{- end }}  {{/* end with printConfigs */}}
{{/* range over tileCloudChainConfigs.sources */}}
{{- with $.Values.config.tileCloudChainConfigs }}
{{- range $name, $value := .sources }}
---
apiVersion: camptocamp.com/v4
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $name ) | nindent 4 }}
    mutualize-sharedconfig{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}
  {{- with $value.external_secret }}
  external_secret:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  content:
    type: git
    repo: git@github.com:{{ $value.repo }}.git
    {{- with $value.branch }}
    branch: {{ . | quote }}
    {{- end }}
    {{- with $value.sub_dir }}
    sub_dir: {{ . | quote }}
    {{- end }}
    tags:
      - tilecloudchain
    {{- if hasKey . "template_engines" }}
    template_engines:
    {{- range $value.template_engines }}
      - type: shell
        environment_variables: true
        {{- with .dest_sub_dir }}
        dest_sub_dir: {{ . | quote }}
        {{- end }}
        {{- with .data }}
        data:
          {{- toYaml . | nindent 10 }}
        {{- end }}
    {{- end }}  {{/* end range over template_engines */}}
    {{- end }}  {{/* end if hasKey . "template_engines" */}}
    auth:
      github_repository: {{ $value.repo }}
      # The type of access to check (admin|push|pull).
      github_access_type: {{ $value.github_access_type | default "push" }}
{{- range $host_name, $host := $value.hosts }}
---
{{- $used_name := printf "%s-%s" $name $host_name }}
apiVersion: camptocamp.com/v4
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" $used_name ) }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values "serviceName" $used_name ) | nindent 4 }}
    mutualize-tilecloudchain-hosts{{ $.Values.postfix }}: 'true'
spec:
  name: {{ $name }}-{{ $host_name }}
  content:
    {{ $host }}: /etc/tilecloudchain-configs/{{ $name }}/config.yaml
{{- end }}  {{/* end range over hosts */}}
{{- end }}  {{/* end range over tileCloudChainConfigs.sources */}}
{{- end }}  {{/* end with tileCloudChainConfigs */}}
{{/* range over redirectConfigs.hosts */}}
{{- with $.Values.config.redirectConfigs }}
{{- if ( .hosts | default false ) }}
---
apiVersion: camptocamp.com/v4
kind: SharedConfigSource{{ $.Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" "redirect" ) }}
  {{- include "common.metadata" ( dict "root" $ "service" $.Values "serviceName" "redirect"  ) | nindent 2 }}
    mutualize-redirect-hosts{{ $.Values.postfix }}: 'true'
spec:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values "serviceName" "redirect" ) }}
  content:
    {{- toYaml .hosts | nindent 4 }}
{{- end }}  {{/* end if ( .hosts | default false ) */}}
{{- end }}  {{/* end range over redirectConfigs.hosts */}}
