{{- if .Values.server.enabled }}
apiVersion: camptocamp.com/v4
kind: SharedConfigConfig{{ .Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.server.sharedConfig "serviceName" "config" ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.server.sharedConfig "serviceName" "config" ) | nindent 2 }}
spec:
  matchLabels:
    mutualize-sharedconfig{{ $.Values.postfix }}: 'true'
  property: sources
  configmapName: config.yaml
  outputKind: ExternalSecret
  refreshInterval: {{ .Values.server.sharedConfig.refreshInterval | default "1h" }}
  {{- with .Values.server.sharedConfig.secretStoreRef }}
  secretStoreRef: {{ . | toYaml | nindent 4 }}
  {{- end }}
  externalSecretPrefix: {{ .Values.server.sharedConfig.externalSecretPrefix | default "config" }}
{{- end }}
