{{- range $name, $value := .Values.additionalConfigs }}
---
apiVersion: camptocamp.com/v2
kind: SharedConfigSource
metadata:
  name: {{ include "common.fullname" ( dict "root" $ "service" $.Values ) }}-{{ $name }}
  labels: {{ include "common.labels" ( dict "root" $ "service" $.Values ) | nindent 4 }}
  {{- range $name, $value := .labels }}
    {{ $name }}: {{ $value | quote }}
  {{- end }}
spec:
  environment: {{ $.Values.environment }}
  name: {{ $name }}
  content:
    {{- toYaml .content | nindent 4 }}
    {{- if hasKey . "env" }}
    template_engines:
      - type: shell
        environment_variables: true
        {{- with .env }}
        data:
          {{- range $name, $value := . }}
          - name: {{ $name | quote }}
            value: {{ . | quote }}
          {{- end }}
        {{- end }}
    {{- end }}
{{- end }}
