{{- if .Values.server.enabled }}
apiVersion: camptocamp.com/v3
kind: SharedConfigConfig{{ .Values.environment | title }}
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.server.sharedConfig ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.server.sharedConfig ) | nindent 2 }}
spec:
  matchLabels:
  {{- if eq $.Values.version "1" }}
    mutualize-sharedconfig: 'true'
  {{- else }}
    mutualize-config: 'true'
    mutualize-version: {{ $.Values.version | quote }}
  {{- end }}
  property: sources
  configmapName: config.yaml
{{- end }}
