apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.config ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.config ) | nindent 2 }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 0 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.config ) | nindent 6 }}
  template:
    metadata: {{- include "common.podMetadata" ( dict "root" . "service" .Values.config ) | nindent 6 }}
    spec:
      {{- include "common.podConfig" ( dict "root" . "service" .Values.config ) | nindent 6 }}
      containers:
        - name: shared-config
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.config ) | nindent 10 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if .Values.prometheus.enabled }}
            - name: prometheus
              containerPort: 9110
              protocol: TCP
{{- end }}
          readinessProbe:
            httpGet:
              path: {{ .Values.config.path }}c2c/health_check
              port: http
            initialDelaySeconds: 10
          volumeMounts:
            - name: ssh-key
              readOnly: true
              mountPath: /var/www/.ssh2
            - name: masterconfig
              readOnly: true
              mountPath: /etc/shared_config_manager
      volumes:
        - name: ssh-key
          secret:
            secretName: {{ include "common.fullname" ( dict "root" . "service" .Values ) }}
            defaultMode: 0440
        - name: masterconfig
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.sharedConfig ) }}
