{{- if .Values.tilecloudchain.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}-main-config
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.tilecloudchain.mainConfig | nindent 4 }}
{{- end }}
