{{- if .Values.tilecloudchain.enabled }}
{{- if .Values.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}-config
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $.Values.tilecloudchain ) | nindent 6 }}
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus-conf
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $.Values.tilecloudchain ) | nindent 6 }}
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchainSlave ) }}-config
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchainSlave ) | nindent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $.Values.tilecloudchainSlave ) | nindent 6 }}
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus-conf
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchainSlave ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchainSlave ) | nindent 2 }}
spec:
  selector:
    matchLabels: {{- include "common.selectorLabels" ( dict "root" $ "service" $.Values.tilecloudchainSlave ) | nindent 6 }}
  podMetricsEndpoints:
    - honorLabels: true
      interval: 10s
      port: prometheus
{{- end }}
{{- end }}
