{{- if .Values.tilecloudchain.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 4 }}
spec:
  type: {{ .Values.tilecloudchain.service.type }}
  ports:
    - port: {{ .Values.tilecloudchain.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "common.selectorLabels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 4 }}
{{- end }}
