{{- if .Values.tilecloudchain.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}
  labels: {{ include "common.labels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 4 }}
  {{- with .Values.tilecloudchain.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.config.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 6 }}
  template:
    metadata:
      labels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 8 }}
      {{- with .Values.tilecloudchain.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- include "common.podConfig" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 6 }}
      containers:
        - name: config
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tilecloudchain.config ) | nindent 10 }}
          args: ['shared-config-slave']
          readinessProbe: &configProbe
            exec:
              command:
                - scm-is-ready
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            <<: *configProbe
            periodSeconds: 120
          volumeMounts:
            - name: configs
              mountPath: /config
            - name: masterconfig
              readOnly: true
              mountPath: /etc/shared_config_manager
        - name: tilecloudchain
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tilecloudchain ) | nindent 10 }}
          volumeMounts:
            - name: configs
              mountPath: /etc/tilecloudchain-configs
            - name: hosts
              mountPath: /etc/tilecloudchain-hosts
            - name: mainconfig
              mountPath: /etc/tilecloudchain-main
            - mountPath: /tmp
              name: tmp-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.tilecloudchain.probes }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
            periodSeconds: 15
          livenessProbe:
            {{- toYaml . | nindent 12 }}
            periodSeconds: 60
          {{- end }}
      volumes:
        - name: configs
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: hosts
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}-hosts
        - name: mainconfig
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}-main-config
        - name: masterconfig
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.config ) }}
{{- end }}
