{{- if .Values.tilecloudchain.enabled -}}
apiVersion: camptocamp.com/v2
kind: SharedConfigConfig
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchainConfig ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchainConfig ) | nindent 2 }}
spec:
  environment: {{ $.Values.environment }}
  matchLabels:
    mutualize-tilecloudchain-hosts: 'true'
  configmapName: hosts.yaml
  property: sources
{{- end }}
