{{- if .Values.tilecloudchain.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}
  {{- include "common.metadata" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 2 }}
spec:
  replicas: {{ .Values.tilecloudchain.replicaCount }}
  revisionHistoryLimit: {{ .Values.global.revisionHistoryLimit | default 0 }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels: {{ include "common.selectorLabels" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 6 }}
  template:
    metadata: {{- include "common.podMetadata" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 6 }}
    spec:
      {{- include "common.podConfig" ( dict "root" . "service" .Values.tilecloudchain ) | nindent 6 }}
      initContainers:
        - name: init-main-config
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tilecloudchainInitMainConfig ) | nindent 10 }}
          {{- with .Values.tilecloudchainInitMainConfig.command }}
          command:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with .Values.tilecloudchainInitMainConfig.args }}
          args:
            {{- . | toYaml | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: originalmainconfig
              mountPath: /etc/tilecloudchain-main-original
            - name: mainconfig
              mountPath: /etc/tilecloudchain-main
      containers:
        - name: config
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tilecloudchain.config ) | nindent 10 }}
          args: ['shared-config-slave']
          readinessProbe: &configProbe
            exec:
              command:
                - scm-is-ready
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            <<: *configProbe
            periodSeconds: 120
          volumeMounts:
            - name: configs
              mountPath: /config
            - name: masterconfig
              readOnly: true
              mountPath: /etc/shared_config_manager
{{- if .Values.prometheus.enabled }}
          ports:
            - name: prometheus-conf
              containerPort: 9111
              protocol: TCP
{{- end }}
        - name: tilecloudchain
          {{- include "common.containerConfig" ( dict "root" . "container" .Values.tilecloudchain ) | nindent 10 }}
          volumeMounts:
            - name: configs
              mountPath: /etc/tilecloudchain-configs
            - name: hosts
              mountPath: /etc/tilecloudchain-hosts
            - name: mainconfig
              mountPath: /etc/tilecloudchain-main
            - mountPath: /tmp
              name: tmp-volume
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
{{- if .Values.prometheus.enabled }}
            - name: prometheus
              containerPort: 9110
              protocol: TCP
{{- end }}
          {{- with .Values.tilecloudchain.probes }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
            periodSeconds: 15
          livenessProbe:
            {{- toYaml . | nindent 12 }}
            periodSeconds: 60
          {{- end }}
      volumes:
        - name: configs
          emptyDir: {}
        - name: tmp-volume
          emptyDir: {}
        - name: mainconfig
          emptyDir: {}
        - name: hosts
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchainConfig ) }}
        - name: originalmainconfig
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.tilecloudchain ) }}-main-config
        - name: masterconfig
          configMap:
            name: {{ include "common.fullname" ( dict "root" . "service" .Values.sharedConfig ) }}
{{- end }}
