#!/usr/bin/env python3

import argparse
import os

import yaml


def _main() -> None:
    parser = argparse.ArgumentParser("Get the version")
    parser.add_argument("--config", default="versions.yaml", help="The versions file to use")
    parser.add_argument("version_name", help="The version name")
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        versions = yaml.load(f, Loader=yaml.SafeLoader)

    if "GITHUB_OUTPUT" in os.environ:
        with open(os.environ["GITHUB_OUTPUT"], "a") as f:
            f.write(f"app={args.version_name}\n")
            f.write(f"version={versions[args.version_name]}\n")


if __name__ == "__main__":
    _main()
