name: Continuous integration

on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+'
    tags:
      - '*'
  pull_request:

permissions:
  actions: write
  contents: write

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-22.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - run: docker system prune --all --force
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pre-commit run --all-files
        env:
          SKIP: helm-lock
      - run: git diff && false
        if: failure()
      - name: Print environment information
        run: c2cciutils-env

      - name: Install helm
        uses: azure/setup-helm@v3
      - run: helm dependency update .
      - run: helm lint .
      - run: helm template test .

      - name: Acceptance tests
        run: make acceptance

      - run: c2cciutils-k8s-logs
        if: always()

      # Just test that we can apply it
      - run: kubectl apply -f tests/alt-expected.yaml

      - run: make acceptance-clean

      - name: Publish
        run: c2cciutils-publish

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        name: Trigger changelog workflow
        uses: actions/github-script@v6
        with:
          script: |-
            if (process.env.GITHUB_REF_TYPE == 'tag') {
                console.log('Trigger changelog');
                await github.rest.repos.createDispatchEvent({
                    owner: 'camptocamp',
                    repo: 'helm-mutualize',
                    event_type: 'changelog',
                });
            }
