---
name: Continuous integration

on:
  push:
  pull_request:

env:
  HAS_SECRETS: ${{ secrets.HAS_SECRETS }}

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 20
    if: "!startsWith(github.event.head_commit.message, '[skip ci] ')"

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: env.HAS_SECRETS == 'HAS_SECRETS'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - name: Install helm
        uses: azure/setup-helm@v1
      - run: helm dependency update .
      - run: helm lint .
      - run: helm template test .

      - run: helm template --namespace=default --values=tests/values.yaml test . > tests/actual.yaml
      - run: diff --ignore-trailing-space tests/actual.yaml tests/expected.yaml
      - run: helm template --namespace=default --values=tests/alt-values.yaml test . > tests/alt-actual.yaml
      - run: diff --ignore-trailing-space tests/alt-actual.yaml tests/alt-expected.yaml

      - name: Setup k3s/k3d
        run: c2cciutils-k8s-install

      - name: Create the database
        run: c2cciutils-k8s-db

      # Install operator
      - run: helm repo add operator-shared-config-manager https://camptocamp.github.io/operator-shared-config-manager
      - run: helm install operator-shared-config-manager --set=image.tag=${VERSION} --version=${VERSION} operator-shared-config-manager/operator-shared-config-manager
        env:
          VERSION: 0.1.1

      # Install Redis
      - run: helm repo add bitnami https://charts.bitnami.com/bitnami
      - run: helm install test-redis --set=auth.enabled=false --set=replica.replicaCount=0 --set=master.persistence.enabled=false bitnami/redis

      - run: kubectl apply -f tests/expected.yaml
      - run: c2cciutils-k8s-wait
      - run: c2cciutils-k8s-logs
        if: always()
      - run: kubectl delete -f tests/expected.yaml || true

      # Just test that we can apply it
      - run: kubectl apply -f tests/alt-expected.yaml

      - run: helm uninstall test-redis

      - name: Publish
        run: c2cciutils-publish
